plugins { id 'base' }
allprojects {
    group = 'panrid.space'
    version = '0.1.0-SNAPSHOT'
    repositories { mavenCentral() }
}
subprojects {
    apply plugin: 'java'
    java { toolchain { languageVersion = JavaLanguageVersion.of(25) } }
    tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
    dependencies {
        testImplementation platform('org.junit:junit-bom:5.13.4')
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }
    tasks.named('test') { useJUnitPlatform() }
}
